packages:
  - packages/*
  - tools/*

catalog:
  '@eslint/js': 9.30.1
  '@types/node': ^22.0.0
  '@vitest/browser': ^3.2.4
  '@vitest/coverage-istanbul': ^3.2.4
  eslint: 9.30.1
  playwright: ^1.53.2
  prettier: ^3.6.2
  rimraf: ^6.0.1
  tslib: ^2.8.1
  tshy: ^3.0.2
  typescript: 5.8.3
  typescript-eslint: 8.36.0
  vitest: ^3.2.4
